"""replace_with_sessions_messages_invest_records

Revision ID: 0778e2b875e3
Revises: 426d6a62c006
Create Date: 2026-03-28 15:26:13.543829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0778e2b875e3'
down_revision: Union[str, Sequence[str], None] = '426d6a62c006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('investor_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'PENDING', 'PASS', 'REJECT', name='sessionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_investor_id'), 'sessions', ['investor_id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('invest_records',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('investor_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False, comment='USDC receiving wallet'),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('funded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_invest_records_investor_id'), 'invest_records', ['investor_id'], unique=False)
    op.create_table('messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # Drop child tables first (FK dependency order)
    op.drop_index(op.f('ix_attachments_pitch_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_pitches_founder_id'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_status'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_term_sheet_id'), table_name='pitches')
    op.drop_table('pitches')
    op.drop_index(op.f('ix_term_sheets_investor_id'), table_name='term_sheets')
    op.drop_index(op.f('ix_term_sheets_status'), table_name='term_sheets')
    op.drop_table('term_sheets')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('founder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('term_sheet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('elevator_pitch', sa.VARCHAR(length=280), autoincrement=False, nullable=True),
    sa.Column('vertical', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stage', postgresql.ENUM('PRE_SEED', 'SEED', 'SERIES_A', 'GROWTH', name='stage'), autoincrement=False, nullable=True),
    sa.Column('github_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('twitter_handle', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'REVIEWING', 'ACCEPTED', 'REJECTED', name='pitchstatus'), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], name=op.f('pitches_founder_id_fkey')),
    sa.ForeignKeyConstraint(['term_sheet_id'], ['term_sheets.id'], name=op.f('pitches_term_sheet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pitches_pkey'))
    )
    op.create_index(op.f('ix_pitches_term_sheet_id'), 'pitches', ['term_sheet_id'], unique=False)
    op.create_index(op.f('ix_pitches_status'), 'pitches', ['status'], unique=False)
    op.create_index(op.f('ix_pitches_founder_id'), 'pitches', ['founder_id'], unique=False)
    op.create_table('attachments',
    sa.Column('pitch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kind', postgresql.ENUM('PITCH_DECK', 'FINANCIALS', 'OTHER', name='attachmentkind'), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name=op.f('attachments_pitch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attachments_pkey'))
    )
    op.create_index(op.f('ix_attachments_pitch_id'), 'attachments', ['pitch_id'], unique=False)
    op.create_table('users',
    sa.Column('wallet_address', sa.VARCHAR(length=42), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('INVESTOR', 'FOUNDER', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('socials', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('deals',
    sa.Column('pitch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('FUNDED', 'ESCROW_RELEASED', 'COMPLETED', 'DISPUTED', name='dealstatus'), autoincrement=False, nullable=False),
    sa.Column('tx_hash', sa.VARCHAR(length=66), autoincrement=False, nullable=True),
    sa.Column('terms_hash', sa.VARCHAR(length=66), autoincrement=False, nullable=True),
    sa.Column('funded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name=op.f('deals_pitch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deals_pkey')),
    sa.UniqueConstraint('pitch_id', name=op.f('deals_pitch_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_table('term_sheets',
    sa.Column('investor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staked_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('valuation_min', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('valuation_max', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('deal_type', postgresql.ENUM('SAFE', 'TOKEN_WARRANT', 'SAFE_TOKEN_WARRANT', 'EQUITY', name='dealtype'), autoincrement=False, nullable=False),
    sa.Column('stage', postgresql.ENUM('PRE_SEED', 'SEED', 'SERIES_A', 'GROWTH', name='stage'), autoincrement=False, nullable=False),
    sa.Column('sectors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thesis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('escrow_address', sa.VARCHAR(length=42), autoincrement=False, nullable=True),
    sa.Column('tx_hash', sa.VARCHAR(length=66), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PAUSED', 'WITHDRAWN', 'FILLED', name='termsheetstatus'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], name=op.f('term_sheets_investor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('term_sheets_pkey'))
    )
    op.create_index(op.f('ix_term_sheets_status'), 'term_sheets', ['status'], unique=False)
    op.create_index(op.f('ix_term_sheets_investor_id'), 'term_sheets', ['investor_id'], unique=False)
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_invest_records_investor_id'), table_name='invest_records')
    op.drop_table('invest_records')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_investor_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
