"""initial_tables

Revision ID: 426d6a62c006
Revises: 
Create Date: 2026-03-28 14:53:15.546435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426d6a62c006'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('INVESTOR', 'FOUNDER', name='userrole'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('socials', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('term_sheets',
    sa.Column('investor_id', sa.UUID(), nullable=False),
    sa.Column('staked_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valuation_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valuation_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deal_type', sa.Enum('SAFE', 'TOKEN_WARRANT', 'SAFE_TOKEN_WARRANT', 'EQUITY', name='dealtype'), nullable=False),
    sa.Column('stage', sa.Enum('PRE_SEED', 'SEED', 'SERIES_A', 'GROWTH', name='stage'), nullable=False),
    sa.Column('sectors', sa.Text(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('escrow_address', sa.String(length=42), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'WITHDRAWN', 'FILLED', name='termsheetstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_sheets_investor_id'), 'term_sheets', ['investor_id'], unique=False)
    op.create_index(op.f('ix_term_sheets_status'), 'term_sheets', ['status'], unique=False)
    op.create_table('pitches',
    sa.Column('founder_id', sa.UUID(), nullable=False),
    sa.Column('term_sheet_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('elevator_pitch', sa.String(length=280), nullable=True),
    sa.Column('vertical', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.Enum('PRE_SEED', 'SEED', 'SERIES_A', 'GROWTH', name='stage'), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWING', 'ACCEPTED', 'REJECTED', name='pitchstatus'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['term_sheet_id'], ['term_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitches_founder_id'), 'pitches', ['founder_id'], unique=False)
    op.create_index(op.f('ix_pitches_status'), 'pitches', ['status'], unique=False)
    op.create_index(op.f('ix_pitches_term_sheet_id'), 'pitches', ['term_sheet_id'], unique=False)
    op.create_table('attachments',
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('PITCH_DECK', 'FINANCIALS', 'OTHER', name='attachmentkind'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_url', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_pitch_id'), 'attachments', ['pitch_id'], unique=False)
    op.create_table('deals',
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('FUNDED', 'ESCROW_RELEASED', 'COMPLETED', 'DISPUTED', name='dealstatus'), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('terms_hash', sa.String(length=66), nullable=True),
    sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pitch_id')
    )
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_attachments_pitch_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_pitches_term_sheet_id'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_status'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_founder_id'), table_name='pitches')
    op.drop_table('pitches')
    op.drop_index(op.f('ix_term_sheets_status'), table_name='term_sheets')
    op.drop_index(op.f('ix_term_sheets_investor_id'), table_name='term_sheets')
    op.drop_table('term_sheets')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
