export interface Accelerator {
  id: string;
  name: string;
  avatar: string;
  tagline: string;
  location: string;
  website: string;
  fundingOffered: string;
  equity: string;
  focus: string[];
  stage: string;
  batchSize: string;
  duration: string;
  programsPerYear: number;
  notablePortfolio: string[];
  thesis: string;
  applyUrl: string;
  quote: string;
  totalFunded: number;
}

export const accelerators: Accelerator[] = [
  {
    id: "y-combinator",
    name: "Y Combinator",
    avatar: "/accelerators/y-combinator.png",
    tagline: "The world's most prestigious startup accelerator",
    location: "San Francisco, CA",
    website: "ycombinator.com",
    fundingOffered: "$500K",
    equity: "7%",
    focus: ["AI/ML", "B2B SaaS", "FinTech", "Consumer", "Deep Tech"],
    stage: "Pre-seed / Seed",
    batchSize: "~250 startups",
    duration: "3 months",
    programsPerYear: 4,
    notablePortfolio: ["Airbnb", "Stripe", "OpenAI", "Coinbase", "DoorDash", "Dropbox", "Reddit", "Instacart"],
    thesis: "We fund the best founders, regardless of industry. Our goal is to work with you on your idea until it's good enough to raise money from investors. We're betting on you — not the market. If the idea is wrong, we think the best founders will figure out the right one.",
    applyUrl: "https://ycombinator.com/apply",
    quote: "Make something people want.",
    totalFunded: 4000,
  },
  {
    id: "techstars",
    name: "Techstars",
    avatar: "/accelerators/techstars.png",
    tagline: "Global mentor-driven accelerator network",
    location: "Global (US, UK, Europe, Asia)",
    website: "techstars.com",
    fundingOffered: "$220K",
    equity: "5%",
    focus: ["Enterprise", "HealthTech", "FinTech", "Energy", "Defense"],
    stage: "Pre-seed / Seed",
    batchSize: "10 startups",
    duration: "3 months",
    programsPerYear: 2,
    notablePortfolio: ["SendGrid", "DigitalOcean", "Sphero", "ClassPass", "Remitly", "PillPack", "DataRobot"],
    thesis: "We believe that entrepreneurs can change the world. Our mentor-driven model connects your startup with the people and capital you need to grow. With 3,200+ companies funded and a network of 10,600+ founders globally, Techstars is the world's largest pre-seed investor by number of investments.",
    applyUrl: "https://techstars.com/entrepreneurs",
    quote: "Do more faster.",
    totalFunded: 3200,
  },
  {
    id: "a16z-speedrun",
    name: "a16z Speedrun",
    avatar: "/accelerators/a16z-speedrun.png",
    tagline: "Andreessen Horowitz's ultra-competitive accelerator",
    location: "San Francisco, CA",
    website: "speedrun.a16z.com",
    fundingOffered: "Up to $1M",
    equity: "10%",
    focus: ["AI", "Enterprise", "Consumer", "Crypto", "Deep Tech"],
    stage: "Pre-seed / Seed",
    batchSize: "<20 startups",
    duration: "12 weeks",
    programsPerYear: 2,
    notablePortfolio: ["150+ startups across 5 cohorts since 2023"],
    thesis: "We accept less than 0.4% of applicants — fewer than Harvard. We prioritize founder backgrounds over ideas and expect most companies to pivot during the program. $180M+ deployed to date. You get the full a16z network: LPs, portfolio, operators, and direct access to the partners who write the big checks.",
    applyUrl: "https://speedrun.a16z.com",
    quote: "Software is eating the world. Now we're looking for who's doing the eating.",
    totalFunded: 150,
  },
  {
    id: "south-park-commons",
    name: "South Park Commons",
    avatar: "/accelerators/south-park-commons.png",
    tagline: "The anti-accelerator for technical founders",
    location: "San Francisco, CA",
    website: "southparkcommons.com",
    fundingOffered: "$1M ($400K + $600K follow-on)",
    equity: "7%",
    focus: ["AI", "Infrastructure", "Enterprise", "Deep Tech", "FinTech"],
    stage: "Pre-seed (idea stage)",
    batchSize: "~20 companies",
    duration: "6 months",
    programsPerYear: 2,
    notablePortfolio: ["Teams from Facebook, Dropbox, Stripe, Planet, Meraki, Pilot"],
    thesis: "We fund -1 to 0: founders who are exploring what to build before they've built it. No pitch deck required. No traction required. Just exceptional people with deep expertise. We call ourselves an anti-accelerator because we don't want to accelerate bad ideas — we want to help great people find the right one.",
    applyUrl: "https://southparkcommons.com/apply",
    quote: "Don't chase the trend. Become the one who creates it.",
    totalFunded: 200,
  },
  {
    id: "neo-residency",
    name: "Neo Residency",
    avatar: "/accelerators/neo-residency.png",
    tagline: "Low-dilution, high-agency technical founder program",
    location: "San Francisco, CA",
    website: "neo.com",
    fundingOffered: "$750K uncapped SAFE + $450K+ compute",
    equity: "Up to 5% at next round",
    focus: ["AI", "Frontier Tech", "Developer Tools", "Enterprise", "Defense"],
    stage: "Pre-seed",
    batchSize: "12–15 startups",
    duration: "3 months + 2-week mountain bootcamp",
    programsPerYear: 2,
    notablePortfolio: ["Cursor", "Kalshi", "Moment (a16z, $56M)", "Anterior (Sequoia + NEA)"],
    thesis: "We target exceptionally high-agency founders. The Neo acceptance signal is so strong that seed investors treat it as institutional validation. Our terms are founder-friendly by design: $750K uncapped SAFE means no artificial valuation cap limits you. We take equity only at your next round — we win when you win.",
    applyUrl: "https://neo.com/apply",
    quote: "The best founders don't need to be accelerated. They need to be resourced.",
    totalFunded: 80,
  },
  {
    id: "hax",
    name: "HAX (by SOSV)",
    avatar: "/accelerators/hax.png",
    tagline: "The world's top hard tech and hardware accelerator",
    location: "Newark, NJ (35,000 sq ft facility)",
    website: "hax.co",
    fundingOffered: "Up to $550K",
    equity: "~7%",
    focus: ["Hardware", "Robotics", "Deep Tech", "Climate Tech", "Industrial"],
    stage: "Pre-seed",
    batchSize: "~15 companies",
    duration: "6 months (residency)",
    programsPerYear: 2,
    notablePortfolio: ["Opentrons", "Upside Foods", "Novoloop", "Prolific Machines", "Ten63"],
    thesis: "Hard tech is hard. Building physical products requires equipment, expertise, and time that most accelerators can't provide. At HAX, you work inside our 35,000 sq ft facility with tools, mentors, and manufacturing connections. 44% of our founders hold PhDs. SOSV portfolio companies raised $7.5B from 2021–2025.",
    applyUrl: "https://hax.co/apply",
    quote: "The atoms-and-bits future is built by people who can do both.",
    totalFunded: 300,
  },
  {
    id: "antler",
    name: "Antler",
    avatar: "/accelerators/antler.png",
    tagline: "Global company builder — no team, no idea required",
    location: "30+ cities globally",
    website: "antler.co",
    fundingOffered: "$400K ($250K + $150K uncapped)",
    equity: "10%",
    focus: ["AI", "Enterprise", "FinTech", "Consumer", "Deep Tech"],
    stage: "Pre-team / Pre-idea",
    batchSize: "~20–40 per city",
    duration: "10 weeks",
    programsPerYear: 2,
    notablePortfolio: ["Lovable (unicorn, 2025)", "Airalo (unicorn)", "Teemyco"],
    thesis: "We back individuals before they have a team or an idea — and help you find the right co-founder during the program. #1 most active global VC in PitchBook's 2024 league table with 443 deals. $1B+ global capital after closing $510M in new funds in January 2026. If you have the potential but not the partner, Antler is for you.",
    applyUrl: "https://antler.co/apply",
    quote: "The world needs more great companies. It starts with great people.",
    totalFunded: 1500,
  },
  {
    id: "yzi-labs",
    name: "YZi Labs (EASY Residency)",
    avatar: "/accelerators/yzi-labs.png",
    tagline: "Web3, AI, and biotech — backed by Binance ecosystem",
    location: "New York / San Francisco / Global",
    website: "yzilabs.com",
    fundingOffered: "$500K ($150K + $350K uncapped)",
    equity: "5%",
    focus: ["Web3", "AI", "Biotech", "DeFi", "Infrastructure"],
    stage: "Pre-seed / Seed",
    batchSize: "Rolling admissions",
    duration: "Year-round (no fixed cohort)",
    programsPerYear: 3,
    notablePortfolio: ["Polygon", "Injective", "SafePal", "Dune Analytics", "300+ projects across 25 countries"],
    thesis: "Formerly Binance Labs — rebranded as YZi Labs in January 2025. EASY Residency operates year-round with rolling entry and three Demo Days per year (TOKEN2049 Dubai, August, December). The Binance ecosystem gives you unmatched distribution for Web3 projects: exchange listings, BNB Chain infrastructure, and global liquidity access.",
    applyUrl: "https://yzilabs.com/easy",
    quote: "The next trillion-dollar companies will be built natively on Web3 rails.",
    totalFunded: 351,
  },
  {
    id: "500-global",
    name: "500 Global",
    avatar: "/accelerators/500-global.png",
    tagline: "The world's most globally distributed startup accelerator",
    location: "Silicon Valley + 75 countries",
    website: "500.co",
    fundingOffered: "$150K",
    equity: "6%",
    focus: ["B2B SaaS", "FinTech", "Consumer", "AI", "HealthTech"],
    stage: "Seed",
    batchSize: "~25 startups",
    duration: "4 months",
    programsPerYear: 2,
    notablePortfolio: ["Canva", "Udemy", "Grab", "Careem", "Aircall", "Talkdesk", "Bukalapak"],
    thesis: "We've funded 2,400+ companies across 75 countries — more than any other accelerator on Earth. Our key differentiator is international distribution: if you're building for emerging markets, Southeast Asia, MENA, or Eurasia, no one has our on-the-ground network. The flagship Silicon Valley program includes intensive customer discovery, PMF, and fundraising curriculum.",
    applyUrl: "https://500.co/founders",
    quote: "Hustle. Connect. Scale.",
    totalFunded: 2400,
  },
  {
    id: "entrepreneur-first",
    name: "Entrepreneur First",
    avatar: "/accelerators/entrepreneur-first.png",
    tagline: "Back talented individuals before they have a team or idea",
    location: "London, Singapore, Bangalore, Paris, Berlin",
    website: "joinef.com",
    fundingOffered: "Up to $250K",
    equity: "8%",
    focus: ["Deep Tech", "AI", "Enterprise", "Biotech", "Developer Tools"],
    stage: "Pre-team / Pre-idea",
    batchSize: "~50 individuals",
    duration: "6 months",
    programsPerYear: 2,
    notablePortfolio: ["Deliveroo", "Cleo AI", "Tractable ($1B+)", "Magic Pony Technology (Twitter $150M)"],
    thesis: "You apply as an individual — not as a team, not with an idea. EF matches you with co-founders. If you're a technical founder in Europe or Southeast Asia, no one has identified more exceptional people from unconventional backgrounds. 637+ companies funded over 13 years. We bet on talent, not traction.",
    applyUrl: "https://joinef.com/apply",
    quote: "The biggest ideas come from people, not markets.",
    totalFunded: 637,
  },
  {
    id: "berkeley-skydeck",
    name: "Berkeley SkyDeck",
    avatar: "/accelerators/berkeley-skydeck.png",
    tagline: "UC Berkeley's top-tier startup accelerator",
    location: "Berkeley, CA (UC Berkeley campus)",
    website: "skydeck.berkeley.edu",
    fundingOffered: "$200K",
    equity: "7.5%",
    focus: ["Deep Tech", "Enterprise", "AI", "Biotech", "Climate"],
    stage: "Pre-seed / Seed",
    batchSize: "20–25 teams",
    duration: "6 months",
    programsPerYear: 2,
    notablePortfolio: ["Xendit", "Squarespace", "Webflow"],
    thesis: "We sit on one of the world's greatest universities — and we use it. UC Berkeley faculty, research, IP, and alumni are embedded in the program. 694 companies funded over 11 years. 2 unicorns. 40+ exits. Our Demo Day draws 900+ investors. If your company has a research component or needs access to Berkeley's scientific infrastructure, SkyDeck is the path.",
    applyUrl: "https://skydeck.berkeley.edu/apply",
    quote: "Research-to-market pipeline, not just a pitch competition.",
    totalFunded: 694,
  },
  {
    id: "ai2-incubator",
    name: "AI2 Incubator",
    avatar: "/accelerators/ai2-incubator.png",
    tagline: "AI-only incubator with $200M compute access",
    location: "Seattle, WA",
    website: "ai2incubator.com",
    fundingOffered: "Up to $600K + $1M+ compute credits",
    equity: "7% + SAFE",
    focus: ["Machine Learning", "NLP", "Computer Vision", "Healthcare AI", "Enterprise AI"],
    stage: "Pre-seed",
    batchSize: "~20/year",
    duration: "Rolling (no fixed cohort)",
    programsPerYear: 4,
    notablePortfolio: ["Yoodli", "Ozette", "WhyLabs", "WellSaid", "Modulus"],
    thesis: "If you're building AI — not 'AI-powered,' actually AI — we're the only accelerator with a $200M compute pool and deep technical mentorship from Oren Etzioni and the Allen Institute for AI team. We closed an $80M third fund in 2025. No required relocation. No mandatory board seats. Pure focus on building the best AI company possible.",
    applyUrl: "https://ai2incubator.com/apply",
    quote: "Real AI, not AI theater.",
    totalFunded: 70,
  },
];

export const acceleratorStats = {
  totalPrograms: "12",
  totalFunded: "12,400+",
  avgEquity: "7.5%",
  topFunding: "Up to $1M",
};
